//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comanda()
        {
            this.Comanda_Meniu_Aux = new HashSet<Comanda_Meniu_Aux>();
            this.Comanda_Preparat_Aux = new HashSet<Comanda_Preparat_Aux>();
        }
    
        public int id_comanda { get; set; }
        public string stare { get; set; }
        public double total_price { get; set; }
        public string data { get; set; }
        public string timp_livrare { get; set; }
        public int utilizator_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comanda_Meniu_Aux> Comanda_Meniu_Aux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comanda_Preparat_Aux> Comanda_Preparat_Aux { get; set; }
        public virtual Utilizator Utilizator { get; set; }
    }
}
