//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meniu_Preparat_Aux
    {
        public int id_meniu_preparat { get; set; }
        public int meniu_id { get; set; }
        public int preparat_id { get; set; }
    
        public virtual Meniu Meniu { get; set; }
        public virtual Preparat Preparat { get; set; }
    }
}
