//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meniu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meniu()
        {
            this.Comanda_Meniu_Aux = new HashSet<Comanda_Meniu_Aux>();
            this.Meniu_Preparat_Aux = new HashSet<Meniu_Preparat_Aux>();
        }
    
        public int id_meniu { get; set; }
        public string nume_meniu { get; set; }
        public double pret { get; set; }
        public int categorie_id { get; set; }
        public string photo { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comanda_Meniu_Aux> Comanda_Meniu_Aux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meniu_Preparat_Aux> Meniu_Preparat_Aux { get; set; }
    }
}
