//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparat_Alergen_Aux
    {
        public int id_preparat_alergen { get; set; }
        public int preparat_id { get; set; }
        public int alergen_id { get; set; }
    
        public virtual Alergen Alergen { get; set; }
        public virtual Preparat Preparat { get; set; }
    }
}
